language: rust

rust:
  - nightly

before_install:
    - sudo apt-get install libpcap-dev

script:
- cargo build
- cargo test --no-run

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  kcov --exclude-pattern=/.cargo target/kcov target/debug/deps/imon-*;
  kcov --exclude-pattern=/.cargo target/kcov target/debug/db_integration-*;
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
